Fiap.Web.App/Fiap.Web.App/Models/CarteiraMotorista.cs
namespace Fiap.Web.App.Models
{
    public class CarteiraMotorista
    {
        public int CarteiraMotoristaId { get; set; }
        public DateTime DataValidade { get; set; }
    }
}

Fiap.Web.App/Fiap.Web.App/Models/Categoria.cs
namespace Fiap.Web.App.Models
{
    public class Categoria
    {
        public int CategoriaId { get; set; }
        public string Nome { get; set; }
    }
}

Fiap.Web.App/Fiap.Web.App/Models/Cliente.cs
namespace Fiap.Web.App.Models
{
    public class Cliente
    {
        //public string Nome { get; set; }
        //public string Sobrenome { get; set; }

        public int ClienteId { get; set; }
        public string Nome { get; set; }
        public virtual ICollection<Qualificacao> Qualificacao { get; set; }

        //one to one
        public CarteiraMotorista Cnh { get; set; }
        public int CarteiraMotoristaId { get; set; }
    }

Fiap.Web.App/Fiap.Web.App/Models/ClienteVeiculo.cs
namespace Fiap.Web.App.Models
{
    public class ClienteVeiculo
    {
        public int ClienteId { get; set; }
        public Cliente Cliente { get; set; }
        public int VeiculoId { get; set; }
        public Veiculo Veiculo { get; set; }
    }
}

Fiap.Web.App/Fiap.Web.App/Models/ErrorViewModel.cs
namespace Fiap.Web.App.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Fiap.Web.App/Fiap.Web.App/Models/Produto.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Fiap.Web.App.Models
{
    public enum Estado
    {
        SP,
        RJ,
        MG
    }
    public class Produto
    {
        [HiddenInput]
        public int ProdutoId { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }

        [Display(Name = "Data de Lançamento")]
        [DataType(DataType.Date)]
        public DateTime DataLancamento { get; set; }
        public decimal Valor { get; set; }
        public Categoria Categoria { get; set; }
        public int? CategoriaId { get; set; }
        public Estado Estado { get; set; }
        public bool Importado { get; set; }
    }
}

Fiap.Web.App/Fiap.Web.App/Models/Qualificacao.cs
namespace Fiap.Web.App.Models
{
    public class Qualificacao
    {
        public int QualificacaoId { get; set; }
        public int Estrelas { get; set; }

    }
}

Fiap.Web.App/Fiap.Web.App/Models/Veiculo.cs
namespace Fiap.Web.App.Models
{
    public class Veiculo
    {
        public int VeiculoId { get; set; }
        public string Modelo { get; set; }
        public ICollection<ClienteVeiculo> ClienteVeiculo { get; set; }
    }
}

Fiap.Web.App/Fiap.Web.App/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;

namespace Fiap.Web.App.Controllers
{
    public class ClienteController : Controller
    {
        public IActionResult Index(string nome, string sobrenome)
        {
            ViewData["chave"] = "Cadastro de Cliente";
            ViewBag.titulo = "Cadastro Cliente";
            TempData["mensagem"] = "Cadastrado com Sucesso!";

            //exercício
            ViewData["nome"] = nome;
            ViewData["sobrenome"] = sobrenome;

            return View();
            //return Content("Olá mundo!");
        }
        public IActionResult Cadastrar()
        {
            return View();
        }
    }
}

Fiap.Web.App/Fiap.Web.App/Controllers/HomeController.cs
using Fiap.Web.App.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Fiap.Web.App.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Fiap.Web.App/Fiap.Web.App/Controllers/ProdutoController.cs
using Fiap.Web.App.Data;
using Fiap.Web.App.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Fiap.Web.App.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly LojaContext _context;
        public ProdutoController(LojaContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {
            Produto produto = new Produto()
            {
                Nome = "Falar para liderar",
                Descricao = "Qualquer descrição aqui",
                Valor = 39,
                Estado = Estado.SP,
                Importado = false
            };
            _context.Produtos.Add(produto);
            _context.SaveChanges();

            return View();
        }
    }
}

Fiap.Web.App/Fiap.Web.App/Controllers/RazorController.cs
using Microsoft.AspNetCore.Mvc;

namespace Fiap.Web.App.Controllers
{
    public class RazorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Fiap.Web.App/Fiap.Web.App/Views/Cliente/Cadastrar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    
    @Html.BeginForm("Cadastrar", "Cliente")
    //@Html.LabelFor(c => c.Nome)
    //@Html.TextBoxFor(c => c.Nome)
    //@Html.EndForm()

}

Fiap.Web.App/Fiap.Web.App/Views/Cliente/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
}

<h1>Teste</h1>
<h3>@ViewData["chave"]</h3>
<h3>@ViewBag.titulo</h3>
<h3>@TempData["mensagem"]</h3>

<br />

<form action = "/Cliente/index" >
<label>Nome</label>
<input type="text" name="nome"/>
<br><br>
<label>Sobrenome</label>
<input type = "text" name="sobrenome"/>
<input type = "submit" value="Enviar"/>
</form>

<br />

<!-- exercício -->
<h2>@ViewData["nome"]</h2>
<h2>@ViewData["sobrenome"]</h2>
<h2>@TempData["mensagem"]</h2>

Fiap.Web.App/Fiap.Web.App/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Fiap.Web.App/Fiap.Web.App/Views/Home/Sucesso.cshtml
@{
    ViewData["Title"] = "Cadastrar Cliente";
}
<h1>@ViewData["Title"]</h1>

<br />

<form action = "/Home/Sucesso.cshtml" >
<label>Nome</label>
<input type="text" name="Nome"/>
<br><br>
<label>Sobrenome</label>
<input type = "text" name="Sobrenome"/>
<br /><br />
<input type = "submit" value="Enviar"/>
</form>

<br />

<!-- exercício -->
<h2>@ViewData["nome"]</h2>
<h2>@ViewData["sobrenome"]</h2>
@TempData["mensagem"]

Fiap.Web.App/Fiap.Web.App/Views/Produto/Cadastrar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    @model Fiap.Web.App.Models.Produto

    <h1>Cadastrouu</h1>

    /*<form asp-action="Cadastrar" asp-controller="Produto">

        <label asp-for="Nome"></label>
        <input asp-for="Nome" />
        <br><br>

        <label asp-for="DataLancamento"></label>
        <input asp-for="DataLancamento" />
        <br><br>

        <label asp-for="Categoria"></label>
        <select asp-for="CategoriaId" asp-items="@ViewBag.categorias">
            <option>Selecione</option>
        </select>
        <br><br>

        <label asp-for="Estado"></label>
        <select asp-for="Estado"
                asp-items="@Html.GetEnumSelectList<Estado>()">
            <option>Selecione</option>
        </select>
        <br><br>

        <input asp-for="Importado" />
        <label asp-for="Importado"></label>
        <br><br>

        <message mensagem='Texto da mensagem'></message>

    </form>
    */
}

Fiap.Web.App/Fiap.Web.App/Views/Razor/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <a asp-action="Index">Home</a>
    <br />
    <br />

    <a asp-controller="Home" asp-action="Index">Home</a>
    <br />
    <br />

    @Html.ActionLink("Texto do Link","Index","Cliente")
    <br />
    <br />
    
    for (int i = 0; i < 10; i++)
    {
        <p>@i</p>
    }
}

Fiap.Web.App/Fiap.Web.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fiap.Web.App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Fiap.Web.App.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Fiap.Web.App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Fiap.Web.App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>